CREATE TABLE TBPRODUTO (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(1000) NOT NULL,
	DT_CRIACAO DATETIME NOT NULL
);

CREATE TABLE TBCOMPRADOR(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL
);

CREATE TABLE TBVENDEDOR(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL
);

CREATE TABLE TBCATEGORIA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL
);



CREATE TABLE TBVENDA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	ID_VENDEDOR BIGINT NOT NULL,
	ID_COMPRADOR BIGINT NOT NULL,
	ID_PRODUTO BIGINT NOT NULL,
	FOREIGN KEY(id_vendedor) REFERENCES TBVENDEDOR(ID),
	FOREIGN KEY(id_comprador) REFERENCES TBCOMPRADOR(ID),
	FOREIGN KEY(id_produto) REFERENCES TBPRODUTO(ID)
);

